### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by SemenMartynov** [oananjeva/trpo#2]
Error message should contain uploaded file name https://github.com/SemenMartynov/SPbPU_TRPO_2017/blob/master/Task01.RUS.txt#L45

**Comment by oananjeva** [comment]
Fixed
![fjpo2szunl8](https://user-images.githubusercontent.com/8788458/35275024-658cdedc-004f-11e8-9a9f-663ef1042890.jpg)

**Comment by SemenMartynov** [comment]
I'm watching your commit `18126c9` and see that you've removed one empty line.
Does it solve this issue somehow?

**Comment by oananjeva** [comment]
This one was made to close this issue.
You can check commit 61157bf where a line with filename was added.

**Comment by SemenMartynov** [comment]
Please provide the format of the message in the form that is described in the task.

Expected:
```
{
 "errorCode"  : 12345,
 "errorMessage" : ["verbose, plain language description of the problem with hints about how to fix it]",
 "errorPlace" : ["highlight the point where error has occurred"],
 "resource"   : ["filename"],
 "request-id" : ["the request id generated by the API for easier tracking of errors"],
}
```

Received:
{
  "CODE: ": 1650220717,
  "MSG AND PLACE: ": "com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 2943 path $.web-app.servlet[4]",
  "RESOURSE": "[json file content]",
  "FILENAME: ": "/bad.json",
  "ID: ": 1
}
