### ISSUE TITLE
Task 2

### ISSUE THREAD

**Issue by SemenMartynov** [oananjeva/trpo#3]
Fix error message and go to the 2nd task.

**Comment by oananjeva** [comment]
Task 2 has been done, please check it.

**Comment by SemenMartynov** [comment]
1. Fix permission
```
$ ./gradlew createImage && docker run -d -p 80:80 jvalid
-bash: ./gradlew: Permission denied
```
2. Complete your documentation
3. Remove build directory from the repo.

**Comment by oananjeva** [comment]
1. Try use `sudo`: `sudo ./gradlew createImage && docker run -d -p 80:80 jvalid`

**Comment by oananjeva** [comment]
1. This error can be fixed by the command:
```
chmod +x gradlew
```
before the
```
./gradlew createImage && docker run -d -p 80:80 jvalid
```
2. README has been updated
3. Removed

**Comment by SemenMartynov** [comment]
1. Follow gitflow with your commits
2. Fix the issue with the gradlew permission.

**Comment by oananjeva** [comment]
It seems that it fixed.

**Comment by SemenMartynov** [comment]
```
$ curl --upload-file bad.json http://localhost
curl: (7) Failed to connect to localhost port 80: Connection refused

```

**Comment by SemenMartynov** [comment]
```
$ docker logs serene_brown 
Error: Unable to access jarfile /build/libs/JValid.jar
```

**Comment by SemenMartynov** [comment]
Any updates?

**Comment by SemenMartynov** [comment]
`Error: Unable to access jarfile target/jvalid-0.0.1-SNAPSHOT-jar-with-dependencies.jar`
Fix this, and check on your side pls.

**Comment by oananjeva** [comment]
Now it must work)

**Comment by SemenMartynov** [comment]
OK
